import type { Order, Tailor } from "./types";

export const demoFxRate = 1600;

export const tailors: Tailor[] = [
  {
    id: "tai_adaobi",
    slug: "adaobi-atelier",
    name: "Adaobi Okeke",
    studio: "Adaobi Atelier",
    location: "Victoria Island, Lagos",
    grade: 5,
    rating: 4.9,
    reviews: 128,
    completedJobs: 214,
    onTimeRate: 97,
    specialties: ["Aso-oke", "Bridal", "Evening wear"],
    startingPriceKobo: 18500000,
    turnaround: "3–5 weeks",
    activeJobs: 14,
    capacity: 20,
    imagePosition: "72% center",
    bio: "Architectural occasionwear, hand-finished in Lagos. Adaobi pairs heritage textiles with precise contemporary silhouettes.",
    verified: true,
  },
  {
    id: "tai_kola",
    slug: "kola-and-sons",
    name: "Kola Adeyemi",
    studio: "Kola & Sons",
    location: "Surulere, Lagos",
    grade: 4,
    rating: 4.8,
    reviews: 86,
    completedJobs: 92,
    onTimeRate: 94,
    specialties: ["Agbada", "Suits", "Menswear"],
    startingPriceKobo: 14000000,
    turnaround: "2–4 weeks",
    activeJobs: 8,
    capacity: 12,
    imagePosition: "51% center",
    bio: "A second-generation house known for quietly confident tailoring, clean shoulders and immaculate embroidery.",
    verified: true,
  },
  {
    id: "tai_amara",
    slug: "amara-studio",
    name: "Amara Nwosu",
    studio: "Amara Studio",
    location: "Lekki, Lagos",
    grade: 3,
    rating: 4.7,
    reviews: 51,
    completedJobs: 47,
    onTimeRate: 91,
    specialties: ["Ready-to-wear", "Dresses", "Adire"],
    startingPriceKobo: 9500000,
    turnaround: "2–3 weeks",
    activeJobs: 4,
    capacity: 7,
    imagePosition: "84% center",
    bio: "Easy, expressive pieces with sculptural lines and a deep affection for locally sourced cloth.",
    verified: true,
  },
  {
    id: "tai_yemi",
    slug: "house-of-yemi",
    name: "Yemi Balogun",
    studio: "House of Yemi",
    location: "Abuja, FCT",
    grade: 2,
    rating: 4.6,
    reviews: 24,
    completedJobs: 18,
    onTimeRate: 88,
    specialties: ["Kaftan", "Embroidery", "Occasion wear"],
    startingPriceKobo: 11000000,
    turnaround: "3–4 weeks",
    activeJobs: 2,
    capacity: 4,
    imagePosition: "40% center",
    bio: "Elegant formalwear built around fluid movement, thoughtful details and warm personal service.",
    verified: true,
  },
];

export const customerOrders: Order[] = [
  {
    id: "ord_01",
    reference: "STL-2408",
    title: "Embroidered wine agbada",
    tailor: "Kola & Sons",
    tailorSlug: "kola-and-sons",
    stage: "sewing",
    dueDate: "Aug 18, 2026",
    amountKobo: 24000000,
    paidKobo: 12000000,
    progress: 58,
  },
  {
    id: "ord_02",
    reference: "STL-2381",
    title: "Ivory civil ceremony dress",
    tailor: "Adaobi Atelier",
    tailorSlug: "adaobi-atelier",
    stage: "finishing",
    dueDate: "Aug 04, 2026",
    amountKobo: 38500000,
    paidKobo: 19250000,
    progress: 82,
  },
];

export const productionStages = [
  { key: "design", label: "Design confirmed" },
  { key: "materials", label: "Materials sourced" },
  { key: "cutting", label: "Cutting" },
  { key: "sewing", label: "Sewing" },
  { key: "fitting", label: "Fitting review" },
  { key: "finishing", label: "Finishing" },
  { key: "ready", label: "Ready" },
  { key: "shipped", label: "Shipped / pickup" },
  { key: "delivered", label: "Delivered" },
] as const;

export const testimonials = [
  {
    quote: "I commissioned my reception look from Toronto and felt present at every stage. The finish was extraordinary.",
    author: "Nneka O.",
    location: "Toronto, Canada",
  },
  {
    quote: "The measurements guide removed the guesswork. My agbada arrived in London and fit beautifully.",
    author: "Tobi A.",
    location: "London, UK",
  },
];
