import Link from "next/link";
import { ArrowRight, Calendar, CheckCircle2, Clock3, MessageCircle, Plus, Ruler, Scissors, Sparkles } from "lucide-react";
import { DashboardHeading, Panel, StatusPill } from "@/components/dashboard-ui";
import { Price } from "@/components/price";
import { ButtonLink } from "@/components/ui/button";
import { customerOrders } from "@/lib/demo-data";

export default async function CustomerDashboard({searchParams}:PageProps<"/customer">){const {created}=await searchParams;return <div className="mx-auto max-w-7xl">{created&&<div className="mb-5 flex items-center gap-3 rounded-xl border border-sage/20 bg-[#e7efe9] p-4 text-sm text-sage"><CheckCircle2 size={18}/> Your request has been posted. Verified tailors can now respond with a quote.</div>}<DashboardHeading eyebrow="Your commissions" title="Everything being made for you." description="Follow progress, payments and conversations without chasing updates." action={<ButtonLink href="/request"><Plus size={16}/> New request</ButtonLink>}/><div className="grid gap-4 lg:grid-cols-[1.5fr_.7fr]">
  <Panel className="overflow-hidden"><div className="flex items-center justify-between border-b border-line p-5"><div><h2 className="font-display text-2xl font-semibold">Active orders</h2><p className="mt-1 text-xs text-muted">2 pieces in production</p></div><Link href="/customer/orders" className="text-xs font-semibold text-wine">View all</Link></div><div className="divide-y divide-line">{customerOrders.map((order)=><Link href={`/customer/orders/${order.id}`} key={order.id} className="group block p-5 hover:bg-background"><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><span className="grid size-12 shrink-0 place-items-center rounded-xl bg-background text-wine"><Scissors size={20}/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold">{order.title}</h3><StatusPill>{order.stage}</StatusPill></div><p className="mt-1 text-xs text-muted">{order.tailor} · {order.reference} · due {order.dueDate}</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-line"><div className="h-full rounded-full bg-wine" style={{width:`${order.progress}%`}}/></div></div><div className="text-right"><Price kobo={order.amountKobo} className="font-semibold"/><p className="mt-1 text-[10px] text-muted">50% paid</p></div><ArrowRight size={16} className="text-muted transition group-hover:translate-x-1 group-hover:text-wine"/></div></Link>)}</div></Panel>
  <div className="space-y-4"><Panel className="p-5"><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-full bg-wine/10 text-wine"><Calendar size={18}/></span><StatusPill tone="green">Confirmed</StatusPill></div><p className="mt-5 text-xs text-muted">Next appointment</p><h2 className="mt-1 font-display text-xl font-semibold">Fit review with Adaobi</h2><p className="mt-2 flex items-center gap-1 text-xs text-muted"><Clock3 size={13}/> Fri, Jul 24 · 4:30 PM WAT</p><button className="mt-5 w-full rounded-full border border-line py-2.5 text-xs font-semibold hover:bg-background">View meeting details</button></Panel><Panel className="p-5"><p className="eyebrow text-wine">Fit profile</p><div className="mt-3 flex items-end justify-between"><div><p className="font-display text-3xl font-semibold">82%</p><p className="text-xs text-muted">12 of 15 measurements</p></div><Ruler className="text-wine"/></div><ButtonLink href="/customer/measurements" variant="secondary" className="mt-5 w-full">Complete profile</ButtonLink></Panel></div>
 </div><div className="mt-4 grid gap-4 lg:grid-cols-3"><Panel className="p-5"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-[#f0e2d0] text-wine"><MessageCircle size={18}/></span><div><p className="font-semibold">2 unread messages</p><p className="text-xs text-muted">Kola sent a production update</p></div></div><Link href="/customer/messages" className="mt-5 flex items-center gap-1 text-xs font-semibold text-wine">Open messages <ArrowRight size={13}/></Link></Panel><Panel className="p-5"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-[#e3eee8] text-sage"><Sparkles size={18}/></span><div><p className="font-semibold">Try-on preview ready</p><p className="text-xs text-muted">See your ivory dress concept</p></div></div><Link href="/customer/try-on" className="mt-5 flex items-center gap-1 text-xs font-semibold text-wine">Open concept preview <ArrowRight size={13}/></Link></Panel><Panel className="bg-wine p-5 text-white"><p className="eyebrow text-[#e2c18f]">Payment protection</p><p className="mt-3 text-sm leading-6 text-white/70">Your ₦312,500 in active order funds remains protected until delivery approval.</p><Link href="/protection" className="mt-4 flex items-center gap-1 text-xs font-semibold">How protection works <ArrowRight size={13}/></Link></Panel></div></div>}
